version: '3.7'

services:
  rabbitmq-ms:
    image: rabbitmq:3-management
    container_name: rabbitmq_microservice
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: always
    environment:
      - TCP_PORTS=15672, 5672
      - RABBITMQ_CONFIG_FILE=/etc/rabbitmq/rabbitmq-test
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log [{console,[{level,debug}]}]
    ports:
      - 15672:15672
      - 5672:5672
    labels:
      com.datadoghq.ad.check_names: '["rabbitmq"]'
      com.datadoghq.ad.instances: '[{"rabbitmq_api_url": "http://%%host%%:15672/api/","username": "guest", "password":"guest"}]'
      com.datadoghq.ad.logs: '[{"source": "rabbitmq", "service": "rabbitmq-ms"}]'

volumes:
  rabbitmq:
    driver: local
