version: "2"
services:
  image-test:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - TOKENACL=${TOKENACL}
      - DiscordToken=${DiscordToken}
      - NotificationSiteUrl=${NotificationSiteUrl}
      - CONSUL_PORT=${CONSUL_PORT}
      - CONSUL_HOST=${CONSUL_HOST}
      - APPLICATION_PORT=${APPLICATION_PORT}

