version: '3'
services:
    microservice-notification:
        image: esgimicroci/al2-notifications:latest
        restart: always
        ports:
            - "8187:8187"
        environment:
          - TOKENACL=${TOKENACL}
          - DiscordToken=${DiscordToken}
          - NotificationSiteUrl=${NotificationSiteUrl}
          - CONSUL_PORT=${CONSUL_PORT}
          - CONSUL_HOST=${CONSUL_HOST}
          - APPLICATION_PORT=${APPLICATION_PORT}
          - NOTIFICATION_RABBITMQ_HOST=${NOTIFICATION_RABBITMQ_HOST}
          - NOTIFICATION_RABBITMQ_PORT=${NOTIFICATION_RABBITMQ_PORT} 
          - NOTIFICATION_RABBITMQ_USERNAME=${NOTIFICATION_RABBITMQ_USERNAME}
          - NOTIFICATION_RABBITMQ_PASSWORD=${NOTIFICATION_RABBITMQ_PASSWORD}
          - MONGO_CONNECTION=${MONGO_CONNECTION}
          - MAIL_HOST=${MAIL_HOST}
          - MAIL_PORT=${MAIL_PORT}
          - MAIL_USERNAME=${MAIL_USERNAME}
          - MAIL_PASSWORD=${MAIL_PASSWORD}
          - MAIL_TO=${MAIL_TO}