name: ESGI Micro CI Notifications

on: [push, pull_request]

jobs:
  build:
    name: Build Micro CI Notifications Project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Maven Package
      run: mvn -B clean package -DskipTests
    - name: Maven Verify
      run: mvn -B clean verify

  # Uncomment and replace {userName} by your account folder name
  deploy:
     name: Build/Publish Docker Images to DockerHub & Deploy to Azure VM
     runs-on: ubuntu-latest
     if: github.ref == 'refs/heads/master'

     steps:
     - name: Checkout Project
       uses: actions/checkout@v1

     - name: Build & Publish Docker Image
       uses: docker/build-push-action@v1
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         repository: micro-ci-al2/micro-ci-notifications
         tag_with_ref: true

     - name: Azure Login
       uses: azure/login@v1
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

     - name: Azure CLI script
       uses: azure/CLI@v1
       with:
         inlineScript: |
            az vm run-command invoke -g ${{ secrets.AZURE_RESOURCE_GRP }} -n ${{ secrets.AZURE_VM }} --command-id RunShellScript --scripts \
            "cd /home/moxa/Bureau/micro-services/micro-ci-notifications && \ 
            wget -q https://raw.githubusercontent.com/esgi-microservices-al2/micro-ci-notifications/master/.github/azure/docker-compose.yml -O docker-compose.yml && \ 
            docker-compose pull microservice-notifications && \
            docker-compose rm -s -f && \
            docker-compose up -d && \
            docker image prune -f --filter "label=MICROSERVICE_NAME=notifications" "
                 
